'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import toast, { Toaster } from 'react-hot-toast';
import styles from './page.module.css';

export default function SettingsPage() {
    const router = useRouter();
    const [importing, setImporting] = useState(false);
    const [file, setFile] = useState(null);
    const [clearExisting, setClearExisting] = useState(false);

    const handleExport = () => {
        // Trigger download programmatically
        window.location.href = '/api/wins/export';
        toast.success('Backup started!');
    };

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
        }
    };

    const handleImport = async () => {
        if (!file) {
            toast.error('Please select a file first');
            return;
        }

        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const content = e.target.result;
                const wins = JSON.parse(content);

                setImporting(true);
                const res = await fetch('/api/wins/import', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ wins, clearExisting }),
                });

                if (res.ok) {
                    const data = await res.json();
                    toast.success(`Successfully imported ${data.count} wins!`);
                    setFile(null);
                    // Reset file input
                    const fileInput = document.getElementById('import-file');
                    if (fileInput) fileInput.value = '';
                } else {
                    const errorData = await res.json();
                    throw new Error(errorData.error || 'Import failed');
                }
            } catch (error) {
                console.error('Import error:', error);
                toast.error('Failed to import: ' + error.message);
            } finally {
                setImporting(false);
            }
        };
        reader.readAsText(file);
    };

    return (
        <div className={styles.container}>
            <header className={styles.header}>
                <Link href="/" className={styles.backButton} aria-label="Back to Dashboard">
                    ←
                </Link>
                <h1 className={styles.title}>Settings</h1>
            </header>

            <main>
                {/* Export Section */}
                <section className={styles.section}>
                    <h2 className={styles.sectionTitle}>📤 Export Data</h2>
                    <p className={styles.description}>
                        Download a copy of all your wins. This JSON file can be used as a backup or to move your data to another device.
                    </p>
                    <button onClick={handleExport} className={styles.buttonPrimary}>
                        Download Backup
                    </button>
                </section>

                {/* Import Section */}
                <section className={styles.section}>
                    <h2 className={styles.sectionTitle}>📥 Import Data</h2>
                    <p className={styles.description}>
                        Restore your wins from a backup file. Supported format: JSON (as generated by the Export feature).
                    </p>

                    <div className={styles.importControls}>
                        <input
                            id="import-file"
                            type="file"
                            accept=".json"
                            onChange={handleFileChange}
                            className={styles.fileInput}
                        />

                        <label className={styles.checkboxLabel}>
                            <input
                                type="checkbox"
                                checked={clearExisting}
                                onChange={(e) => setClearExisting(e.target.checked)}
                            />
                            <span>Clear existing wins before importing (Replace all data)</span>
                        </label>

                        {clearExisting && (
                            <div className={styles.dangerZone}>
                                ⚠️ Warning: This will delete all current wins in the database before importing. This action cannot be undone.
                            </div>
                        )}

                        <button
                            onClick={handleImport}
                            disabled={!file || importing}
                            className={styles.buttonPrimary}
                            style={{ opacity: !file || importing ? 0.6 : 1 }}
                        >
                            {importing ? 'Importing...' : 'Import Wins'}
                        </button>
                    </div>
                </section>
            </main>
            <Toaster position="bottom-center" />
        </div>
    );
}
